package:
  name: openpathsampling-dev
  version: "0.9.1"

source:
#  git_url: ../../.git
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - numpy
    - scipy
    - pandas
    - netcdf4
    - openmm
    - openmmtools
    - pyyaml
    - mdtraj
    - svgwrite
    - networkx
    - pyqt 4.11.4 py27_3
    - matplotlib
    - ujson

test:
  imports:
    - openpathsampling

about:
  home: http://github.com/openpathsampling/openpathsampling
  license: LGPL 2.1 or later
  summary: 'OpenPathSampling: A python package to do path sampling simulations'
